# Generated by Django 2.2.12 on 2022-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash', '0002_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
