# Generated by Django 4.1.1 on 2022-09-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash', '0003_auto_20220919_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
